# Generated by Django 4.2.21 on 2025-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_description_product_image_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
